import typography from "@tailwindcss/typography";

/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "#9facf4",
        "background": "#0c0e14",
        "surface": "#0c0e14",
        "tertiary-container": "#e1af7e",
        "on-secondary-fixed": "#004843",
        "on-primary": "#283575",
        "on-secondary-container": "#4bb4aa",
        "surface-variant": "#222631",
        "surface-bright": "#272c39",
        "on-surface": "#e2e5f4",
        "tertiary": "#f0bd8b",
        "on-primary-fixed-variant": "#334080",
        "tertiary-dim": "#ca9a6b",
        "surface-container-high": "#1c1f29",
        "on-surface-variant": "#a7aab9",
        "surface-tint": "#aebaff",
        "on-secondary-fixed-variant": "#006760",
        "on-error-container": "#ff97a3",
        "outline": "#717583",
        "secondary-dim": "#62c9bf",
        "on-primary-fixed": "#122161",
        "on-secondary": "#004944",
        "surface-container": "#161922",
        "error": "#fd6f85",
        "secondary-fixed-dim": "#7fe6db",
        "surface-container-lowest": "#000000",
        "primary-fixed": "#b2bdff",
        "on-tertiary-fixed-variant": "#5a3811",
        "inverse-primary": "#4d5b9c",
        "inverse-on-surface": "#53555c",
        "surface-dim": "#0c0e14",
        "on-tertiary-container": "#502f09",
        "error-container": "#8a1632",
        "on-tertiary": "#5b3912",
        "primary-dim": "#929fe6",
        "secondary": "#71d7cd",
        "outline-variant": "#444854",
        "surface-container-highest": "#222631",
        "on-primary-container": "#1d2b6a",
        "primary": "#aebaff",
        "primary-fixed-dim": "#a2aff7",
        "inverse-surface": "#faf8ff",
        "on-background": "#e2e5f4",
        "error-dim": "#c8475d",
        "on-error": "#490013",
        "tertiary-fixed": "#e1af7e",
        "tertiary-fixed-dim": "#d3a272",
        "on-tertiary-fixed": "#331b00",
        "secondary-fixed": "#8ef4e9",
        "surface-container-low": "#11131a",
        "secondary-container": "#002b28",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Manrope", "sans-serif"],
      },
    },
  },
  plugins: [typography],
};
