"""Industry-to-RSS-feed mapping. Constants only — no logic."""

INDUSTRY_FEEDS = {
    "Business Intelligence & Analytics": [
        "https://towardsdatascience.com/feed",
        "https://www.datasciencecentral.com/feed/",
        "https://www.analyticsvidhya.com/feed/",
        "https://blog.hubspot.com/analytics/rss.xml",
        "https://hnrss.org/newest?q=business+intelligence&points=10",
        "https://hnrss.org/newest?q=data+analytics&points=10",
        "https://hnrss.org/newest?q=BI+tools&points=10",
    ],
    "Data Engineering & Infrastructure": [
        "https://www.dataengineeringweekly.com/feed",
        "https://www.getdbt.com/blog/rss.xml",
        "https://www.snowflake.com/blog/feed/",
        "https://cloud.google.com/blog/products/data-analytics/rss",
        "https://hnrss.org/newest?q=data+engineering&points=10",
        "https://hnrss.org/newest?q=data+pipeline&points=10",
        "https://hnrss.org/newest?q=data+warehouse&points=10",
    ],
    "Marketing & Advertising": [
        "https://blog.hubspot.com/marketing/rss.xml",
        "https://moz.com/blog/feed",
        "https://www.searchenginejournal.com/feed/",
        "https://contentmarketinginstitute.com/feed/",
        "https://hnrss.org/newest?q=digital+marketing&points=10",
        "https://hnrss.org/newest?q=ad+tech&points=10",
    ],
    "E-commerce & Retail": [
        "https://www.shopify.com/blog/feed",
        "https://www.practicalecommerce.com/feed",
        "https://www.digitalcommerce360.com/feed/",
        "https://hnrss.org/newest?q=ecommerce&points=10",
        "https://hnrss.org/newest?q=online+retail&points=10",
    ],
    "Finance & Accounting": [
        "https://www.cfo.com/feed/",
        "https://www.financial-planning.com/feed",
        "https://www.accountingtoday.com/feed",
        "https://hnrss.org/newest?q=fintech&points=10",
        "https://hnrss.org/newest?q=financial+modeling&points=10",
        "https://hnrss.org/newest?q=accounting+software&points=10",
    ],
    "SaaS & Technology": [
        "https://www.saastr.com/feed/",
        "https://techcrunch.com/category/saas/feed/",
        "https://tomtunguz.com/feed/",
        "https://hnrss.org/newest?q=SaaS&points=10",
        "https://hnrss.org/newest?q=startup+tools&points=10",
    ],
    "AI & Machine Learning": [
        "https://news.mit.edu/topic/mitartificial-intelligence2-rss.xml",
        "https://machinelearningmastery.com/feed/",
        "https://www.marktechpost.com/feed/",
        "https://theaibeat.com/feed/",
        "https://hnrss.org/newest?q=machine+learning&points=10",
        "https://hnrss.org/newest?q=LLM&points=10",
        "https://hnrss.org/newest?q=AI+tools&points=10",
    ],
    "Sales & Revenue Operations": [
        "https://www.saleshacker.com/feed/",
        "https://www.gong.io/blog/feed/",
        "https://blog.close.com/rss/",
        "https://hnrss.org/newest?q=sales+automation&points=10",
        "https://hnrss.org/newest?q=CRM&points=10",
    ],
    "Supply Chain & Operations": [
        "https://www.supplychaindive.com/feeds/news/",
        "https://www.logisticsmgmt.com/rss",
        "https://scm.ncsu.edu/scm-articles/feed",
        "https://hnrss.org/newest?q=supply+chain&points=10",
        "https://hnrss.org/newest?q=logistics+software&points=10",
    ],
    "HR & People Analytics": [
        "https://www.shrm.org/rss/pages/custom-rss-feeds.aspx",
        "https://www.hrdive.com/feeds/news/",
        "https://www.tlnt.com/feed/",
        "https://hnrss.org/newest?q=HR+tech&points=10",
        "https://hnrss.org/newest?q=people+analytics&points=10",
    ],
    "Agency & Consulting": [
        "https://www.consultancy.uk/feed",
        "https://agencyland.co/feed/",
        "https://www.marketingprofs.com/syndication/rss",
        "https://hnrss.org/newest?q=consulting&points=10",
        "https://hnrss.org/newest?q=agency+tools&points=10",
    ],
    "Small Business & Entrepreneurship": [
        "https://smallbiztrends.com/feed",
        "https://www.entrepreneur.com/latest/feed",
        "https://startupsmagazine.co.uk/feed",
        "https://hnrss.org/newest?q=small+business&points=10",
        "https://hnrss.org/newest?q=bootstrapped&points=10",
        "https://hnrss.org/newest?q=solopreneur&points=10",
    ],
}

DEFAULT_FEEDS = [
    "https://towardsdatascience.com/feed",
    "https://www.analyticsvidhya.com/feed/",
    "https://techcrunch.com/category/saas/feed/",
    "https://hnrss.org/newest?q=startup&points=10",
]
