import React, { useState } from "react";
import { Copy, Download, Mail } from "lucide-react";
import { StepProgress, Spinner } from "./LoadingStates";
import AUDIENCES from "../audiences";

export default function NarrativePanel({ apiBase, audience, profile, signals, analysis, gaps, onNarrative }) {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(null);
  const [result, setResult] = useState(null);
  const [copied, setCopied] = useState(false);
  const [activeQuestion, setActiveQuestion] = useState(null);
  const [followUpLoading, setFollowUpLoading] = useState(false);
  const [followUpAnswer, setFollowUpAnswer] = useState(null);
  const [followUpError, setFollowUpError] = useState(null);
  const [compareAudience, setCompareAudience] = useState(null);
  const [compareResult, setCompareResult] = useState(null);
  const [compareLoading, setCompareLoading] = useState(false);
  const [compareError, setCompareError] = useState(null);

  const canRun = signals && analysis;
  const audienceLabel = AUDIENCES.find((a) => a.id === audience)?.label ?? audience;
  const compareLabel = AUDIENCES.find((a) => a.id === compareAudience)?.label ?? compareAudience;

  async function handleGenerate() {
    if (!canRun) return;
    setLoading(true);
    setError(null);
    setResult(null);
    setActiveQuestion(null);
    setFollowUpAnswer(null);
    setFollowUpError(null);
    setCompareAudience(null);
    setCompareResult(null);
    setCompareError(null);
    try {
      const res = await fetch(`${apiBase}/api/narrative`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ audience, signals, analysis, gaps, profile }),
      });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      setResult(data);
      if (onNarrative) onNarrative(data);
    } catch (err) {
      setError(err.message);
    } finally {
      setLoading(false);
    }
  }

  async function handleCompare() {
    if (!compareAudience) return;
    setCompareLoading(true);
    setCompareResult(null);
    setCompareError(null);
    try {
      const res = await fetch(`${apiBase}/api/narrative`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ audience: compareAudience, signals, analysis, gaps, profile }),
      });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      setCompareResult(data);
    } catch (err) {
      setCompareError(err.message);
    } finally {
      setCompareLoading(false);
    }
  }

  async function handleFollowUp(question) {
    setActiveQuestion(question);
    setFollowUpLoading(true);
    setFollowUpAnswer(null);
    setFollowUpError(null);
    try {
      const res = await fetch(`${apiBase}/api/narrative/follow-up`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          audience,
          question,
          briefing: result.briefing,
          signals,
          analysis,
          gaps,
          profile,
        }),
      });
      if (!res.ok) throw new Error(await res.text());
      const data = await res.json();
      setFollowUpAnswer(data.answer);
    } catch (err) {
      setFollowUpError(err.message);
    } finally {
      setFollowUpLoading(false);
    }
  }

  function handleCopy() {
    navigator.clipboard.writeText(result.briefing).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  }

  function handleDownloadPDF() {
    const title = `${audienceLabel} Briefing — Prism Intelligence`;
    const html = `<!DOCTYPE html>
<html><head><meta charset="UTF-8"><title>${title}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
         color: #111; margin: 40px; line-height: 1.6; font-size: 14px; }
  h1 { font-size: 20px; margin-bottom: 4px; }
  .meta { font-size: 12px; color: #666; margin-bottom: 24px; }
  .content { white-space: pre-wrap; }
</style></head><body>
<h1>${title}</h1>
<div class="meta">Generated by Prism Enterprise Intelligence Platform</div>
<div class="content">${result.briefing.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")}</div>
</body></html>`;

    const iframe = document.createElement("iframe");
    iframe.style.position = "fixed";
    iframe.style.top = "-10000px";
    iframe.style.left = "-10000px";
    iframe.style.width = "800px";
    iframe.style.height = "600px";
    document.body.appendChild(iframe);

    iframe.contentDocument.open();
    iframe.contentDocument.write(html);
    iframe.contentDocument.close();

    iframe.contentWindow.focus();
    iframe.contentWindow.print();

    setTimeout(() => document.body.removeChild(iframe), 1000);
  }

  function handleEmail() {
    const subject = encodeURIComponent(`Prism Intelligence Briefing — ${audienceLabel}`);
    const maxBodyLength = 1800;
    let bodyText = result.briefing;
    if (bodyText.length > maxBodyLength) {
      bodyText = bodyText.slice(0, maxBodyLength) + "\n\n[Briefing truncated — paste full text from Prism]";
    }
    const body = encodeURIComponent(bodyText);
    window.location.href = `mailto:?subject=${subject}&body=${body}`;
  }

  const isComparing = !!compareResult;

  return (
    <div className={`space-y-6 ${isComparing ? "max-w-5xl" : "max-w-3xl"}`}>
      <div>
        <h2 className="text-lg font-semibold text-gray-100">Narrative Engine</h2>
        <p className="text-sm text-gray-400 mt-1">
          Generate an executive briefing tailored for the <span className="text-indigo-400 font-medium">{audienceLabel}</span> role.
        </p>
      </div>

      {!canRun && (
        <div className="rounded-md border border-yellow-800 bg-yellow-950 px-4 py-3 text-sm text-yellow-300">
          Complete both Signal Collection and Data Analysis before generating narratives.
        </div>
      )}

      <button
        onClick={handleGenerate}
        disabled={!canRun || loading}
        className="rounded-md bg-indigo-600 px-5 py-2 text-sm font-medium text-white hover:bg-indigo-500 disabled:opacity-40 transition-colors"
      >
        {loading ? "Generating..." : `Generate ${audienceLabel} Briefing`}
      </button>

      {error && (
        <div className="rounded-md bg-red-950 border border-red-800 px-4 py-3 text-sm text-red-300">
          {error}
        </div>
      )}

      {loading && (
        <StepProgress
          steps={[
            "Assembling intelligence context...",
            "Generating executive briefing with AI...",
          ]}
          active={loading}
        />
      )}

      {result && !loading && (
        <>
          {/* Heading row + compare dropdown */}
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <h3 className="text-sm font-semibold text-indigo-400">
                {audienceLabel} Briefing
              </h3>
              <span className="text-xs px-2 py-0.5 rounded-full border border-indigo-800 text-indigo-400">
                Prism Intelligence
              </span>
            </div>
            <div className="flex items-center gap-2">
              <select
                value={compareAudience || ""}
                onChange={(e) => {
                  setCompareAudience(e.target.value || null);
                  setCompareResult(null);
                  setCompareError(null);
                }}
                className="rounded-md bg-gray-800 border border-gray-700 px-3 py-1.5 text-xs text-gray-100 focus:outline-none focus:ring-2 focus:ring-indigo-500"
              >
                <option value="">Compare with...</option>
                {AUDIENCES.filter((a) => a.id !== audience).map((a) => (
                  <option key={a.id} value={a.id}>
                    {a.label}
                  </option>
                ))}
              </select>
              <button
                onClick={handleCompare}
                disabled={!compareAudience || compareLoading}
                className="inline-flex items-center gap-1.5 rounded-md bg-indigo-600 px-3 py-1.5 text-xs font-medium text-white hover:bg-indigo-500 disabled:opacity-40 transition-colors"
              >
                {compareLoading && <Spinner size="sm" />}
                {compareLoading ? "Comparing..." : "Compare"}
              </button>
            </div>
          </div>

          {compareError && (
            <div className="rounded-md bg-red-950 border border-red-800 px-4 py-3 text-sm text-red-300">
              {compareError}
            </div>
          )}

          {/* Follow-up question chips */}
          {result.follow_up_questions?.length > 0 && (
            <div className="space-y-3">
              <p className="text-xs font-medium text-gray-400">What would you ask next?</p>
              <div className="flex flex-wrap gap-2">
                {result.follow_up_questions.map((q, i) => (
                  <button
                    key={i}
                    onClick={() => handleFollowUp(q)}
                    disabled={followUpLoading}
                    className={`inline-flex items-center gap-1.5 text-left text-xs px-3 py-2 rounded-lg border transition-colors ${
                      activeQuestion === q
                        ? "border-indigo-500 bg-indigo-950 text-indigo-300"
                        : "border-gray-700 bg-gray-900 text-gray-300 hover:border-gray-500 hover:text-gray-200"
                    } disabled:opacity-50`}
                  >
                    {followUpLoading && activeQuestion === q && <Spinner size="sm" />}
                    {q}
                  </button>
                ))}
              </div>

              {followUpError && (
                <div className="rounded-md bg-red-950 border border-red-800 px-4 py-3 text-sm text-red-300">
                  {followUpError}
                </div>
              )}

              {followUpAnswer && (
                <div className="rounded-lg border border-gray-800 bg-gray-900 p-4">
                  <p className="text-xs font-medium text-indigo-400 mb-2">{activeQuestion}</p>
                  <div className="text-sm text-gray-300 whitespace-pre-wrap leading-relaxed">
                    {followUpAnswer}
                  </div>
                </div>
              )}
            </div>
          )}

          {/* Briefing text — side by side when comparing */}
          {isComparing ? (
            <div className="grid grid-cols-2 gap-4">
              <div className="rounded-lg border border-gray-800 bg-gray-900 p-5">
                <p className="text-xs font-medium text-indigo-400 mb-3">{audienceLabel}</p>
                <div className="text-sm text-gray-300 whitespace-pre-wrap leading-relaxed">
                  {result.briefing}
                </div>
              </div>
              <div className="rounded-lg border border-gray-800 bg-gray-900 p-5">
                <p className="text-xs font-medium text-indigo-400 mb-3">{compareLabel}</p>
                <div className="text-sm text-gray-300 whitespace-pre-wrap leading-relaxed">
                  {compareResult.briefing}
                </div>
              </div>
            </div>
          ) : (
            <div className="rounded-lg border border-gray-800 bg-gray-900 p-5">
              <div className="text-sm text-gray-300 whitespace-pre-wrap leading-relaxed">
                {result.briefing}
              </div>
            </div>
          )}

          {/* Export buttons */}
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopy}
              className={`inline-flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-xs transition-colors ${
                copied
                  ? "border-green-700 text-green-400"
                  : "border-gray-700 text-gray-400 hover:border-gray-500 hover:text-gray-200"
              }`}
            >
              <Copy size={14} />
              {copied ? "Copied" : "Copy"}
            </button>
            <button
              onClick={handleDownloadPDF}
              className="inline-flex items-center gap-1.5 rounded-md border border-gray-700 px-3 py-1.5 text-xs text-gray-400 hover:border-gray-500 hover:text-gray-200 transition-colors"
            >
              <Download size={14} />
              Download PDF
            </button>
            <button
              onClick={handleEmail}
              className="inline-flex items-center gap-1.5 rounded-md border border-gray-700 px-3 py-1.5 text-xs text-gray-400 hover:border-gray-500 hover:text-gray-200 transition-colors"
            >
              <Mail size={14} />
              Email Draft
            </button>
          </div>
        </>
      )}
    </div>
  );
}
